#!/usr/bin/env node

import { createInterface } from "node:readline";
import { existsSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const ENV_PATH = resolve(ROOT, ".env.local");

const rl = createInterface({ input: process.stdin, output: process.stdout });

function ask(prompt) {
  return new Promise((res) => {
    rl.question(prompt, (answer) => res(answer));
  });
}

function isValidUrl(value) {
  return /^https?:\/\/.+/.test(value);
}

async function askRequired(prompt, validate) {
  while (true) {
    const answer = (await ask(prompt)).trim();
    if (!answer) {
      console.log("  이 항목은 필수입니다. 다시 입력해주세요.");
      continue;
    }
    if (validate && !validate(answer)) {
      continue;
    }
    return answer;
  }
}

async function askOptional(prompt, defaultValue) {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = (await ask(`${prompt}${suffix}: `)).trim();
  return answer || defaultValue || "";
}

async function askOptionalUrl(prompt, defaultValue) {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  while (true) {
    const answer = (await ask(`${prompt}${suffix}: `)).trim();
    if (!answer) return defaultValue || "";
    if (!isValidUrl(answer)) {
      console.log("  URL은 http:// 또는 https://로 시작해야 합니다.");
      continue;
    }
    return answer;
  }
}

async function askYesNo(prompt, defaultNo = true) {
  const suffix = defaultNo ? " (y/N)" : " (Y/n)";
  const answer = (await ask(`${prompt}${suffix}: `)).trim().toLowerCase();
  if (!answer) return !defaultNo;
  return answer === "y" || answer === "yes";
}

async function main() {
  console.log("");
  console.log("  SentinAI Environment Setup");
  console.log("");

  // Check existing .env.local
  if (existsSync(ENV_PATH)) {
    const overwrite = await askYesNo("? 이미 .env.local이 존재합니다. 덮어쓰시겠습니까?");
    if (!overwrite) {
      console.log("  취소되었습니다.");
      rl.close();
      return;
    }
    console.log("");
  }

  const env = {};

  // --- 1. L2 RPC (Required) ---
  console.log("  --- 1. L2 Chain RPC ---");
  env.L2_RPC_URL = await askRequired("? L2 RPC URL (필수): ", (v) => {
    if (!isValidUrl(v)) {
      console.log("  URL은 http:// 또는 https://로 시작해야 합니다.");
      return false;
    }
    return true;
  });
  console.log("");

  // --- 2. AI Configuration ---
  console.log("  --- 2. AI Configuration ---");
  env.AI_GATEWAY_URL = await askOptionalUrl(
    "? AI Gateway URL",
    "https://api.ai.tokamak.network"
  );
  env.ANTHROPIC_API_KEY = await askRequired("? Anthropic API Key (필수): ");
  console.log("");

  // --- 3. K8s Configuration ---
  const setupK8s = await askYesNo("? K8s 모니터링 설정하시겠습니까?");

  if (setupK8s) {
    console.log("");
    console.log("  --- 3. Kubernetes Configuration ---");
    env.K8S_NAMESPACE = await askOptional("? K8s Namespace", "default");
    env.K8S_APP_PREFIX = await askOptional("? K8s App Prefix", "op");
    console.log("");

    // --- 4. AWS EKS ---
    console.log("  --- 4. AWS EKS Connection ---");
    env.K8S_API_URL = await askOptionalUrl("? K8s API URL (EKS endpoint)");
    env.AWS_CLUSTER_NAME = await askOptional("? AWS Cluster Name");
    env.AWS_REGION = await askOptional("? AWS Region", "ap-northeast-2");
    env.AWS_ACCESS_KEY_ID = await askOptional("? AWS Access Key ID");
    env.AWS_SECRET_ACCESS_KEY = await askOptional("? AWS Secret Access Key");
  }

  console.log("");

  // Build file content
  const lines = [
    "# ==========================================",
    "# SentinAI Configuration",
    "# Generated by: npm run setup",
    "# ==========================================",
    "",
    "# --- 1. L2 Chain RPC (Required) ---",
    `L2_RPC_URL=${env.L2_RPC_URL}`,
    "",
    "# --- 2. AI Configuration (Required for Log Analysis) ---",
  ];

  if (env.AI_GATEWAY_URL) {
    lines.push(`AI_GATEWAY_URL=${env.AI_GATEWAY_URL}`);
  } else {
    lines.push("# AI_GATEWAY_URL=https://api.ai.tokamak.network");
  }
  lines.push(`ANTHROPIC_API_KEY=${env.ANTHROPIC_API_KEY}`);

  if (setupK8s) {
    lines.push("");
    lines.push("# --- 3. Kubernetes Configuration ---");
    lines.push(`K8S_NAMESPACE=${env.K8S_NAMESPACE || "default"}`);
    lines.push(`K8S_APP_PREFIX=${env.K8S_APP_PREFIX || "op"}`);
    lines.push("");
    lines.push("# --- 4. AWS EKS Connection ---");
    if (env.K8S_API_URL) lines.push(`K8S_API_URL=${env.K8S_API_URL}`);
    if (env.AWS_CLUSTER_NAME) lines.push(`AWS_CLUSTER_NAME=${env.AWS_CLUSTER_NAME}`);
    lines.push(`AWS_REGION=${env.AWS_REGION || "ap-northeast-2"}`);
    if (env.AWS_ACCESS_KEY_ID) lines.push(`AWS_ACCESS_KEY_ID=${env.AWS_ACCESS_KEY_ID}`);
    if (env.AWS_SECRET_ACCESS_KEY) lines.push(`AWS_SECRET_ACCESS_KEY=${env.AWS_SECRET_ACCESS_KEY}`);
  }

  lines.push("");

  writeFileSync(ENV_PATH, lines.join("\n"), "utf-8");

  console.log("  \u2713 .env.local 생성 완료");
  console.log("  npm run dev 로 서버를 시작하세요.");
  console.log("");

  rl.close();
}

main().catch((err) => {
  console.error("Setup 오류:", err.message);
  rl.close();
  process.exit(1);
});
